#  Predicting House Sale Prices

## Introduction

We'll work with housing data for the city of Ames, Iowa, United States from 2006 to 2010. You can read more about why the data was collected [here](https://www.tandfonline.com/doi/abs/10.1080/10691898.2011.11889627). You can also read about the different columns in the data [here](https://s3.amazonaws.com/dq-content/307/data_description.txt).

Let's start by setting up a pipeline of functions that will let us quickly iterate on different models.

![pipeline](pipeline.svg)

In [48]:
import pandas as pd
pd.options.display.max_columns = 999
pd.options.display.max_rows = 999
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [49]:
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")
print(df.shape)
df.head()

(2930, 82)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.0,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.0,Unf,0.0,441.0,1080.0,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.0,0.0,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.0,Fin,2.0,528.0,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,None,0.0,Gd,TA,CBlock,TA,TA,No,ALQ,1065.0,Unf,0.0,1045.0,2110.0,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.0,0.0,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.0,Fin,2.0,522.0,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [50]:
### Function that, for now, just returns the train data frame.
def transform_features(df):
    return df

In [51]:
### Function that, for now, just returns the 'Gr Liv Area' and 'SalePric'e columns from the train data frame
def select_features(df):
    return df[["Gr Liv Area", "SalePrice"]]

In [52]:
### Function that, for now, creates train and test set, trains model and return RMSE after prediction
def train_and_test(df): 
    df = df.select_dtypes(include=['integer', 'float'])
    train = df[:1460]
    test = df[1460:]
    
    features = train.columns.drop("SalePrice")
    lr = linear_model.LinearRegression()
    lr.fit(train[features], train["SalePrice"])
    predictions = lr.predict(test[features])
    mse = mean_squared_error(test["SalePrice"], predictions)
    rmse = np.sqrt(mse)
    
    return rmse

In [53]:
### Working check
transform_df = transform_features(df)
filtered_df = select_features(transform_df)
rmse = train_and_test(filtered_df)
rmse

57088.25161263909

## Feature Engineering

Let's now start removing features with many missing values, diving deeper into potential categorical features, and transforming text and numerical columns. We are going to update `transform_features()` so that any column from the data frame with more than 25% missing values is dropped. We also need to remove any columns that leak information about the sale (e.g. like the year the sale happened). 

All columns: Drop any with 25% or more missing values.

In [54]:
num_missing = df.isnull().sum()
drop_missing_cols = num_missing[(num_missing > len(df)/4)]
df = df.drop(drop_missing_cols.index, axis=1)
drop_missing_cols

Alley           2732
Fireplace Qu    1422
Pool QC         2917
Fence           2358
Misc Feature    2824
dtype: int64

For columns with missing values, fill in with the most common value in that column.

In [55]:
num_missing = df.isnull().sum()
replacement_values_dict = df[num_missing.index].mode().to_dict(orient='records')[0]
replacement_values_dict

{'Order': 1,
 'PID': 526301100,
 'MS SubClass': 20.0,
 'MS Zoning': 'RL',
 'Lot Frontage': 60.0,
 'Lot Area': 9600.0,
 'Street': 'Pave',
 'Lot Shape': 'Reg',
 'Land Contour': 'Lvl',
 'Utilities': 'AllPub',
 'Lot Config': 'Inside',
 'Land Slope': 'Gtl',
 'Neighborhood': 'NAmes',
 'Condition 1': 'Norm',
 'Condition 2': 'Norm',
 'Bldg Type': '1Fam',
 'House Style': '1Story',
 'Overall Qual': 5.0,
 'Overall Cond': 5.0,
 'Year Built': 2005.0,
 'Year Remod/Add': 1950.0,
 'Roof Style': 'Gable',
 'Roof Matl': 'CompShg',
 'Exterior 1st': 'VinylSd',
 'Exterior 2nd': 'VinylSd',
 'Mas Vnr Type': 'None',
 'Mas Vnr Area': 0.0,
 'Exter Qual': 'TA',
 'Exter Cond': 'TA',
 'Foundation': 'PConc',
 'Bsmt Qual': 'TA',
 'Bsmt Cond': 'TA',
 'Bsmt Exposure': 'No',
 'BsmtFin Type 1': 'GLQ',
 'BsmtFin SF 1': 0.0,
 'BsmtFin Type 2': 'Unf',
 'BsmtFin SF 2': 0.0,
 'Bsmt Unf SF': 0.0,
 'Total Bsmt SF': 0.0,
 'Heating': 'GasA',
 'Heating QC': 'Ex',
 'Central Air': 'Y',
 'Electrical': 'SBrkr',
 '1st Flr SF': 864.0,
 '2nd Flr SF': 0.0,
 'Low Qual Fin SF': 0.0,
 'Gr Liv Area': 864.0,
 'Bsmt Full Bath': 0.0,
 'Bsmt Half Bath': 0.0,
 'Full Bath': 2.0,
 'Half Bath': 0.0,
 'Bedroom AbvGr': 3.0,
 'Kitchen AbvGr': 1.0,
 'Kitchen Qual': 'TA',
 'TotRms AbvGrd': 6.0,
 'Functional': 'Typ',
 'Fireplaces': 0.0,
 'Garage Type': 'Attchd',
 'Garage Yr Blt': 2005.0,
 'Garage Finish': 'Unf',
 'Garage Cars': 2.0,
 'Garage Area': 0.0,
 'Garage Qual': 'TA',
 'Garage Cond': 'TA',
 'Paved Drive': 'Y',
 'Wood Deck SF': 0.0,
 'Open Porch SF': 0.0,
 'Enclosed Porch': 0.0,
 '3Ssn Porch': 0.0,
 'Screen Porch': 0.0,
 'Pool Area': 0.0,
 'Misc Val': 0.0,
 'Mo Sold': 6.0,
 'Yr Sold': 2007.0,
 'Sale Type': 'WD ',
 'Sale Condition': 'Normal',
 'SalePrice': 135000.0}

In [56]:
### Replace missing values with their column mode
df = df.fillna(replacement_values_dict)

### Verify every column has 0 missing values
df.isnull().sum().value_counts()

0    77
dtype: int64

What new features can we create, that better capture the information in some of the features? We can find house age by subtracting year of built from year of sold.

In [57]:
years_sold = df['Yr Sold'] - df['Year Built']
years_sold[years_sold < 0]

2180   -1
dtype: int64

In [58]:
years_since_remod = df['Yr Sold'] - df['Year Remod/Add']
years_since_remod[years_since_remod < 0]

1702   -1
2180   -2
2181   -1
dtype: int64

In [59]:
### Create new columns
df['Years Before Sale'] = years_sold
df['Years Since Remod'] = years_since_remod

### Drop rows with negative values for these features
df = df.drop([1702, 2180, 2181], axis=0)

### Drop original year columns
df = df.drop(["Year Built", "Year Remod/Add"], axis = 1)

Now let's drop columns that:
- aren't useful for ML
- leak data about the final sale

In [60]:
### Drop columns useless for ML
df = df.drop(["PID", "Order"], axis=1)

### Drop columns that leak info about the final sale
df = df.drop(["Mo Sold", "Sale Condition", "Sale Type", "Yr Sold"], axis=1)

Let's update `transform_features()` and check how did our changes impact the RMSE.

In [61]:
def transform_features(df):
    ### Drop any with 25% or more missing values
    num_missing = df.isnull().sum()
    drop_missing_cols = num_missing[(num_missing > len(df)/4)]
    df = df.drop(drop_missing_cols.index, axis=1)
    
    num_missing = df.isnull().sum()
    replacement_values_dict = df[num_missing.index].mode().to_dict(orient='records')[0]
    ### Replace missing values with their column mode
    df = df.fillna(replacement_values_dict)
    
    years_sold = df['Yr Sold'] - df['Year Built']
    years_since_remod = df['Yr Sold'] - df['Year Remod/Add']
    df['Years Before Sale'] = years_sold
    df['Years Since Remod'] = years_since_remod
    df = df.drop([1702, 2180, 2181], axis=0)

    df = df.drop(["Mo Sold", "Sale Condition", "Sale Type", "Yr Sold", "Year Built", 
                  "Year Remod/Add", "PID", "Order"], axis=1)
    return df

In [62]:
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")
transform_df = transform_features(df)
filtered_df = select_features(transform_df)
rmse = train_and_test(filtered_df)
rmse

55275.367312413066

## Feature Selection

Now that we have cleaned and transformed a lot of the features in the data set, it's time to move on to feature selection for numerical features.

In [69]:
numerical_df = transform_df.select_dtypes(include=['int64', 'float64'])
numerical_df.head()

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,SalePrice,Years Before Sale,Years Since Remod
0,20,141.0,31770,6,5,112.0,639.0,0.0,441.0,1080.0,1656,0,0,1656,1.0,0.0,1,0,3,1,7,2,1960.0,2.0,528.0,210,62,0,0,0,0,0,215000,50,50
1,20,80.0,11622,5,6,0.0,468.0,144.0,270.0,882.0,896,0,0,896,0.0,0.0,1,0,2,1,5,0,1961.0,1.0,730.0,140,0,0,0,120,0,0,105000,49,49
2,20,81.0,14267,6,6,108.0,923.0,0.0,406.0,1329.0,1329,0,0,1329,0.0,0.0,1,1,3,1,6,0,1958.0,1.0,312.0,393,36,0,0,0,0,12500,172000,52,52
3,20,93.0,11160,7,5,0.0,1065.0,0.0,1045.0,2110.0,2110,0,0,2110,1.0,0.0,2,1,3,1,8,2,1968.0,2.0,522.0,0,0,0,0,0,0,0,244000,42,42
4,60,74.0,13830,5,5,0.0,791.0,0.0,137.0,928.0,928,701,0,1629,0.0,0.0,2,1,3,1,6,1,1997.0,2.0,482.0,212,34,0,0,0,0,0,189900,13,12

In [70]:
abs_corr_coeffs = numerical_df.corr()['SalePrice'].abs().sort_values()
abs_corr_coeffs

BsmtFin SF 2         0.006127
Misc Val             0.019273
3Ssn Porch           0.032268
Bsmt Half Bath       0.035875
Low Qual Fin SF      0.037629
Pool Area            0.068438
MS SubClass          0.085128
Overall Cond         0.101540
Screen Porch         0.112280
Kitchen AbvGr        0.119760
Enclosed Porch       0.128685
Bedroom AbvGr        0.143916
Bsmt Unf SF          0.182751
Lot Area             0.267520
2nd Flr SF           0.269601
Bsmt Full Bath       0.276258
Half Bath            0.284871
Open Porch SF        0.316262
Wood Deck SF         0.328183
Lot Frontage         0.333681
BsmtFin SF 1         0.439284
Garage Yr Blt        0.442216
Fireplaces           0.474831
TotRms AbvGrd        0.498574
Mas Vnr Area         0.506983
Years Since Remod    0.534985
Full Bath            0.546118
Years Before Sale    0.558979
1st Flr SF           0.635185
Garage Area          0.641425
Total Bsmt SF        0.644012
Garage Cars          0.648361
Gr Liv Area          0.717596
Overall Qual         0.801206
SalePrice            1.000000
Name: SalePrice, dtype: float64

Let's only keep columns with a correlation coefficient of larger than 0.2

In [74]:
transform_df = transform_df.drop(abs_corr_coeffs[abs_corr_coeffs < 0.2].index, axis=1)

- Which columns are currently numerical but need to be encoded as categorical instead (because the numbers don't have any semantic meaning)?
- If a categorical column has hundreds of unique values (or categories), should we keep it? When we dummy code this column, hundreds of columns will need to be added back to the data frame.

In [76]:
### Create a list of column names from documentation that are meant to be categorical
nominal_features = ["PID", "MS SubClass", "MS Zoning", "Street", "Alley", "Land Contour", "Lot Config", "Neighborhood", 
                    "Condition 1", "Condition 2", "Bldg Type", "House Style", "Roof Style", "Roof Matl", "Exterior 1st", 
                    "Exterior 2nd", "Mas Vnr Type", "Foundation", "Heating", "Central Air", "Garage Type", 
                    "Misc Feature", "Sale Type", "Sale Condition"]

### Which categorical columns have we still carried with us?
transform_cat_cols = []
for col in nominal_features:
    if col in transform_df.columns:
        transform_cat_cols.append(col)

### How many unique values in each categorical column?
uniqueness_counts = transform_df[transform_cat_cols].apply(lambda col: len(col.value_counts())).sort_values()
### Aribtrary cutoff of 10 unique values
drop_nonuniq_cols = uniqueness_counts[uniqueness_counts > 10].index
transform_df = transform_df.drop(drop_nonuniq_cols, axis=1)

In [77]:
### Select just the remaining text columns and convert to categorical
text_cols = transform_df.select_dtypes(include=['object'])
for col in text_cols:
    transform_df[col] = transform_df[col].astype('category')
    
### Create dummy columns and add back to the dataframe
transform_df = pd.concat([transform_df, 
                          pd.get_dummies(transform_df.select_dtypes(include=['category']))
                         ], axis=1).drop(text_cols, axis=1)

Update the logic for the `select_features()` function

In [79]:
def select_features(df, coeff_threshold=0.2, uniq_threshold=10):
    numerical_df = df.select_dtypes(include=['int64', 'float64'])
    abs_corr_coeffs = numerical_df.corr()['SalePrice'].abs().sort_values()
    df = df.drop(abs_corr_coeffs[abs_corr_coeffs < coeff_threshold].index, axis=1)
    
    nominal_features = ["PID", "MS SubClass", "MS Zoning", "Street", "Alley", "Land Contour", "Lot Config", "Neighborhood", 
                    "Condition 1", "Condition 2", "Bldg Type", "House Style", "Roof Style", "Roof Matl", "Exterior 1st", 
                    "Exterior 2nd", "Mas Vnr Type", "Foundation", "Heating", "Central Air", "Garage Type", 
                    "Misc Feature", "Sale Type", "Sale Condition"]
    
    transform_cat_cols = []
    for col in nominal_features:
        if col in df.columns:
            transform_cat_cols.append(col)

    uniqueness_counts = df[transform_cat_cols].apply(lambda col: len(col.value_counts())).sort_values()
    drop_nonuniq_cols = uniqueness_counts[uniqueness_counts > uniq_threshold].index
    df = df.drop(drop_nonuniq_cols, axis=1)
    
    text_cols = df.select_dtypes(include=['object'])
    for col in text_cols:
        df[col] = df[col].astype('category')
    df = pd.concat([df, pd.get_dummies(df.select_dtypes(include=['category']))], axis=1).drop(text_cols, axis=1)
    
    return df

## Train And Test

Now for the final part of the pipeline, training and testing. When iterating on different features, using simple validation is a good idea. Let's add a parameter named `k` that controls the type of cross validation that occurs.

- When `k` equals `0`, perform holdout validation (what we already implemented)


- When `k` equals `1`, perform simple cross validation


- When `k` is greater than `0`, implement k-fold cross validation using `k` folds

In [91]:
def train_and_test(df, k=0):
    numeric_df = df.select_dtypes(include=['integer', 'float'])
    features = numeric_df.columns.drop("SalePrice")
    lr = linear_model.LinearRegression()
    
    if k == 0:
        train = df[:1460]
        test = df[1460:]

        lr.fit(train[features], train["SalePrice"])
        predictions = lr.predict(test[features])
        mse = mean_squared_error(test["SalePrice"], predictions)
        rmse = np.sqrt(mse)

        return rmse
    
    if k == 1:
        # Randomize *all* rows (frac=1) from `df` and return
        shuffled_df = df.sample(frac=1)
        train = df[:1460]
        test = df[1460:]
        
        lr.fit(train[features], train["SalePrice"])
        predictions_one = lr.predict(test[features])        
        
        mse_one = mean_squared_error(test["SalePrice"], predictions_one)
        rmse_one = np.sqrt(mse_one)
        
        lr.fit(test[features], test["SalePrice"])
        predictions_two = lr.predict(train[features])        
       
        mse_two = mean_squared_error(train["SalePrice"], predictions_two)
        rmse_two = np.sqrt(mse_two)
        
        avg_rmse = np.mean([rmse_one, rmse_two])
#         print(rmse_one)
#         print(rmse_two)
        return avg_rmse
    else:
        kf = KFold(n_splits=k, shuffle=True, random_state=1)
        rmse_values = []
        for train_index, test_index, in kf.split(df):
            train = df.iloc[train_index]
            test = df.iloc[test_index]
            lr.fit(train[features], train["SalePrice"])
            predictions = lr.predict(test[features])
            mse = mean_squared_error(test["SalePrice"], predictions)
            rmse = np.sqrt(mse)
            rmse_values.append(rmse)
#         print(rmse_values)
        avg_rmse = np.mean(rmse_values)
        return avg_rmse

Let's experiment now, exploring different feature engineering parameters: correlation coefficient and uniqueness thresholds. The number of fold in cross validation will be set as `10`.

In [94]:
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")
transform_df = transform_features(df)
filtered_df = select_features(transform_df, coeff_threshold=0.2, uniq_threshold=10)
rmse = train_and_test(filtered_df, k=10)
rmse

27005.52777483003

In [95]:
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")
transform_df = transform_features(df)
filtered_df = select_features(transform_df, coeff_threshold=0.1, uniq_threshold=10)
rmse = train_and_test(filtered_df, k=10)
rmse

26361.980784116906

In [105]:
df = pd.read_csv("AmesHousing.tsv", delimiter="\t")
transform_df = transform_features(df)
filtered_df = select_features(transform_df, coeff_threshold=0.1, uniq_threshold=30)
rmse = train_and_test(filtered_df, k=10)
rmse

25044.982856034436

In [110]:
"{:.2%}".format(rmse / filtered_df["SalePrice"].mean())

'14.75%'

## Conclusions 

Thus, we were able to improve the results of the model up to **RMSE equals 25 000$**, which is about `15%` of mean sale price, by reducing correlation coefficient threshold and extending uniqueness threshold.